name: Publish Native Android Library

on:
  push:
    branches: [ mavencentral-publish ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x ./android/gradlew
    - name: Grant execute permission for publishing script
      run: chmod +x ./scripts/publish-android.sh
    - name: Run publish script
      working-directory: ./scripts
      env:
        OSSRH_USERNAME: ${{ secrets.ANDROID_OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.ANDROID_OSSRH_PASSWORD }}
        SIGNING_KEY_ID: ${{ secrets.ANDROID_SIGNING_KEY_ID }}
        SIGNING_PASSWORD: ${{ secrets.ANDROID_SIGNING_PASSWORD }}
        SIGNING_KEY: ${{ secrets.ANDROID_SIGNING_KEY }}
        SONATYPE_STAGING_PROFILE_ID: ${{ secrets.ANDROID_SONATYPE_STAGING_PROFILE_ID }}
      run: ./publish-android.sh
